version: '3'

services:
  postgres: # hostname
    image: postgres
    environment: # default user is postgres
      POSTGRES_PASSWORD: "pass123"
      POSTGRES_DB: "cubejs-test" #database name
    ports:
      - "5432:5432"
    networks:
      - shared-networks    

  cube:
    container_name: api
    image: cubejs/cube:v0.30.3
    restart: always
    ports:
      - 4000:4000  # Dashboard app, if created
    env_file: .env
    volumes:
      - .:/cube/conf
      - .empty:/cube/conf/node_modules/@cubejs-backend/
    depends_on:
      - postgres
    networks:
      - shared-networks

  client:
    container_name: client
    image: cubejs-client-prod:1.0.0
    build:
        context: client
        dockerfile: Dockerfile
    volumes:
      - node_modules:/usr/src/client/node_modules
    ports: 
      - 3000:3000
    networks:
      - shared-networks
    depends_on:
      - cube
networks:
  shared-networks: